---
# Tasks for backend deployment
- name: Create backend directory
  ansible.builtin.file:
    path: /home/ig/backend
    state: directory
    mode: '0755'

- name: Pull and run backend container
  community.docker.docker_container:
    name: backend
    image: "{{ backend_image_url }}"
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
